import type {
  User,
  Firm,
  FirmMembership,
  Project,
  ProjectMembership,
  Phase,
  Decision,
  Quotation,
  QuotationLine,
  ChangeOrder,
  Invoice,
  Channel,
  ChannelMembership,
  Message,
  ProjectFile,
  Defect,
  AuditLog,
} from './types';

export const mockClient: User = {
  id: 'usr-001',
  email: 'sarah.tan@gmail.com',
  phone: '+6591234567',
  full_name: 'Sarah Tan',
  avatar_url: null,
  created_at: '2026-02-10T08:30:00.000Z',
};

export const mockDesigner: User = {
  id: 'usr-002',
  email: 'marcus@studiomori.sg',
  phone: '+6598765432',
  full_name: 'Marcus Chen',
  avatar_url: null,
  created_at: '2025-06-15T03:00:00.000Z',
};

export const mockFirm: Firm = {
  id: 'frm-001',
  name: 'Studio Mori',
  slug: 'studio-mori',
  logo_url: null,
  uen: '202312345A',
  plan: 'beta',
  created_at: '2025-06-15T03:00:00.000Z',
};

export const mockFirmMembership: FirmMembership = {
  id: 'fmb-001',
  firm_id: 'frm-001',
  user_id: 'usr-002',
  role: 'admin',
  created_at: '2025-06-15T03:00:00.000Z',
};

export const mockProject: Project = {
  id: 'prj-001',
  firm_id: 'frm-001',
  name: 'Tan family — Tampines Block 678 #04-12',
  property_type: 'hdb',
  address: 'Block 678 Tampines Street 61, #04-12, Singapore 520678',
  unit_size_sqft: 990,
  status: 'active',
  planned_start_date: '2026-03-03',
  planned_end_date: '2026-06-20',
  actual_start_date: '2026-03-03',
  actual_end_date: null,
  created_by: 'usr-002',
  created_at: '2026-02-15T06:00:00.000Z',
  deleted_at: null,
};

export const mockProjectMemberships: ProjectMembership[] = [
  {
    id: 'pmb-001',
    project_id: 'prj-001',
    user_id: 'usr-001',
    role: 'client',
    trade: null,
    status: 'active',
    invited_email: 'sarah.tan@gmail.com',
    invited_phone: '+6591234567',
    invited_by: 'usr-002',
    joined_at: '2026-02-16T02:15:00.000Z',
    created_at: '2026-02-15T06:30:00.000Z',
  },
  {
    id: 'pmb-002',
    project_id: 'prj-001',
    user_id: 'usr-002',
    role: 'designer',
    trade: null,
    status: 'active',
    invited_email: 'marcus@studiomori.sg',
    invited_phone: null,
    invited_by: 'usr-002',
    joined_at: '2026-02-15T06:00:00.000Z',
    created_at: '2026-02-15T06:00:00.000Z',
  },
];

export const mockPhases: Phase[] = [
  {
    id: 'phs-001',
    project_id: 'prj-001',
    name: 'Hacking',
    description: 'Demolition of existing walls, flooring, and built-in fixtures',
    sequence: 1,
    planned_start: '2026-03-03',
    planned_end: '2026-03-14',
    actual_start: '2026-03-03',
    actual_end: '2026-03-13',
    status: 'complete',
    created_at: '2026-02-15T06:00:00.000Z',
    updated_at: '2026-03-13T10:00:00.000Z',
  },
  {
    id: 'phs-002',
    project_id: 'prj-001',
    name: 'Masonry',
    description: 'Brickwork, wall erection, and waterproofing for wet areas',
    sequence: 2,
    planned_start: '2026-03-17',
    planned_end: '2026-03-28',
    actual_start: '2026-03-17',
    actual_end: '2026-03-29',
    status: 'complete',
    created_at: '2026-02-15T06:00:00.000Z',
    updated_at: '2026-03-29T10:00:00.000Z',
  },
  {
    id: 'phs-003',
    project_id: 'prj-001',
    name: 'Plumbing',
    description: 'Piping rough-in for kitchen, bathrooms, and service yard',
    sequence: 3,
    planned_start: '2026-03-31',
    planned_end: '2026-04-11',
    actual_start: '2026-03-31',
    actual_end: '2026-04-10',
    status: 'complete',
    created_at: '2026-02-15T06:00:00.000Z',
    updated_at: '2026-04-10T10:00:00.000Z',
  },
  {
    id: 'phs-004',
    project_id: 'prj-001',
    name: 'Electrical',
    description: 'Wiring, DB box, power points, lighting points, and data cabling',
    sequence: 4,
    planned_start: '2026-04-13',
    planned_end: '2026-04-24',
    actual_start: '2026-04-13',
    actual_end: null,
    status: 'in_progress',
    created_at: '2026-02-15T06:00:00.000Z',
    updated_at: '2026-04-13T08:00:00.000Z',
  },
  {
    id: 'phs-005',
    project_id: 'prj-001',
    name: 'Carpentry',
    description: 'Kitchen cabinets, wardrobes, shoe cabinet, TV console, and feature wall',
    sequence: 5,
    planned_start: '2026-04-27',
    planned_end: '2026-05-22',
    actual_start: null,
    actual_end: null,
    status: 'pending',
    created_at: '2026-02-15T06:00:00.000Z',
    updated_at: null,
  },
  {
    id: 'phs-006',
    project_id: 'prj-001',
    name: 'Painting',
    description: 'Wall preparation, plastering, primer, and two coats of emulsion paint',
    sequence: 6,
    planned_start: '2026-05-25',
    planned_end: '2026-06-05',
    actual_start: null,
    actual_end: null,
    status: 'pending',
    created_at: '2026-02-15T06:00:00.000Z',
    updated_at: null,
  },
  {
    id: 'phs-007',
    project_id: 'prj-001',
    name: 'Defect Period',
    description: 'Final inspection, touch-ups, and defect rectification',
    sequence: 7,
    planned_start: '2026-06-08',
    planned_end: '2026-06-20',
    actual_start: null,
    actual_end: null,
    status: 'pending',
    created_at: '2026-02-15T06:00:00.000Z',
    updated_at: null,
  },
];

export const mockDecisions: Decision[] = [
  {
    id: 'dec-001',
    project_id: 'prj-001',
    phase_id: 'phs-005',
    title: 'Master bedroom wardrobe laminate finish',
    description: 'Select laminate finish for the 8-foot built-in wardrobe in the master bedroom. See attached samples from Jennings Laminates catalogue.',
    options: [
      { label: 'Walnut Woodgrain (WG-4412)', cost_delta: 0 },
      { label: 'Scandinavian Oak (SO-2208)', cost_delta: 180 },
      { label: 'Matte Charcoal (MC-1001)', cost_delta: 120 },
    ],
    deadline: '2026-04-18',
    status: 'decided',
    decided_value: { label: 'Scandinavian Oak (SO-2208)', cost_delta: 180 },
    decided_at: '2026-04-16T09:30:00.000Z',
    decided_by: 'usr-001',
    created_by: 'usr-002',
    created_at: '2026-04-10T07:00:00.000Z',
  },
  {
    id: 'dec-002',
    project_id: 'prj-001',
    phase_id: 'phs-003',
    title: 'Kitchen sink and tap set',
    description: 'Choose between the Franke and Blanco sink-tap bundles. Both are undermount single bowl.',
    options: [
      { label: 'Franke Mythos MYX 110-50 + Lina pull-out tap', cost_delta: 0 },
      { label: 'Blanco Subline 500-U + Mida-S tap', cost_delta: 220 },
    ],
    deadline: '2026-03-25',
    status: 'decided',
    decided_value: { label: 'Franke Mythos MYX 110-50 + Lina pull-out tap', cost_delta: 0 },
    decided_at: '2026-03-22T14:00:00.000Z',
    decided_by: 'usr-001',
    created_by: 'usr-002',
    created_at: '2026-03-18T04:00:00.000Z',
  },
  {
    id: 'dec-003',
    project_id: 'prj-001',
    phase_id: 'phs-004',
    title: 'Living room feature wall power point layout',
    description: 'Confirm number and positions of power points behind the TV console. Electrician needs this before cabling is concealed.',
    options: [
      { label: '4 points in a row (standard)', cost_delta: 0 },
      { label: '6 points in two clusters', cost_delta: 80 },
    ],
    deadline: '2026-04-15',
    status: 'overdue',
    decided_value: null,
    decided_at: null,
    decided_by: null,
    created_by: 'usr-002',
    created_at: '2026-04-08T03:00:00.000Z',
  },
  {
    id: 'dec-004',
    project_id: 'prj-001',
    phase_id: 'phs-006',
    title: 'Living and dining area paint colour',
    description: 'Select wall paint colour for living room, dining area, and corridor. Nippon Paint Odourless All-in-1 range.',
    options: [
      { label: 'Brilliant White (OW1001P)', cost_delta: 0 },
      { label: 'Grey Dew (NP OW 1032P)', cost_delta: 0 },
      { label: 'Soft Oat (NP N 1843P)', cost_delta: 0 },
    ],
    deadline: '2026-05-10',
    status: 'pending',
    decided_value: null,
    decided_at: null,
    decided_by: null,
    created_by: 'usr-002',
    created_at: '2026-04-20T06:00:00.000Z',
  },
  {
    id: 'dec-005',
    project_id: 'prj-001',
    phase_id: 'phs-002',
    title: 'Service yard glass panel enclosure',
    description: 'Originally discussed enclosing the service yard with a glass panel. Client decided to keep it open.',
    options: [
      { label: 'Install tempered glass panel', cost_delta: 1800 },
      { label: 'Leave open (no change)', cost_delta: 0 },
    ],
    deadline: '2026-03-20',
    status: 'not_needed',
    decided_value: null,
    decided_at: null,
    decided_by: null,
    created_by: 'usr-002',
    created_at: '2026-03-10T05:00:00.000Z',
  },
];

export const mockFiles: ProjectFile[] = [
  {
    id: 'fil-001',
    project_id: 'prj-001',
    uploaded_by: 'usr-002',
    name: 'Quotation_TanFamily_v1.pdf',
    storage_path: 'projects/prj-001/quotation/Quotation_TanFamily_v1.pdf',
    mime_type: 'application/pdf',
    size_bytes: 284672,
    category: 'quotation',
    tags: ['quotation', 'v1', 'accepted'],
    created_at: '2026-02-20T04:00:00.000Z',
    deleted_at: null,
  },
  {
    id: 'fil-002',
    project_id: 'prj-001',
    uploaded_by: 'usr-002',
    name: 'Renovation_Contract_Signed.pdf',
    storage_path: 'projects/prj-001/contract/Renovation_Contract_Signed.pdf',
    mime_type: 'application/pdf',
    size_bytes: 512000,
    category: 'contract',
    tags: ['contract', 'signed'],
    created_at: '2026-02-22T09:00:00.000Z',
    deleted_at: null,
  },
  {
    id: 'fil-003',
    project_id: 'prj-001',
    uploaded_by: 'usr-002',
    name: 'Kitchen_3D_Render_Final.jpg',
    storage_path: 'projects/prj-001/renders/Kitchen_3D_Render_Final.jpg',
    mime_type: 'image/jpeg',
    size_bytes: 2457600,
    category: 'render',
    tags: ['kitchen', '3d-render', 'approved'],
    created_at: '2026-02-25T07:30:00.000Z',
    deleted_at: null,
  },
  {
    id: 'fil-004',
    project_id: 'prj-001',
    uploaded_by: 'usr-002',
    name: 'HDB_Renovation_Permit.pdf',
    storage_path: 'projects/prj-001/permits/HDB_Renovation_Permit.pdf',
    mime_type: 'application/pdf',
    size_bytes: 198400,
    category: 'permit',
    tags: ['hdb', 'permit', 'approved'],
    created_at: '2026-02-28T02:00:00.000Z',
    deleted_at: null,
  },
  {
    id: 'fil-005',
    project_id: 'prj-001',
    uploaded_by: 'usr-002',
    name: 'Master_Bedroom_Layout_v2.jpg',
    storage_path: 'projects/prj-001/renders/Master_Bedroom_Layout_v2.jpg',
    mime_type: 'image/jpeg',
    size_bytes: 1843200,
    category: 'render',
    tags: ['master-bedroom', 'layout', 'v2'],
    created_at: '2026-03-01T05:00:00.000Z',
    deleted_at: null,
  },
  {
    id: 'fil-006',
    project_id: 'prj-001',
    uploaded_by: 'usr-001',
    name: 'PayNow_Receipt_Invoice1.jpg',
    storage_path: 'projects/prj-001/receipts/PayNow_Receipt_Invoice1.jpg',
    mime_type: 'image/jpeg',
    size_bytes: 340992,
    category: 'receipt',
    tags: ['receipt', 'paynow', 'deposit'],
    created_at: '2026-03-02T11:00:00.000Z',
    deleted_at: null,
  },
  {
    id: 'fil-007',
    project_id: 'prj-001',
    uploaded_by: 'usr-002',
    name: 'Electrical_Layout_Plan.pdf',
    storage_path: 'projects/prj-001/permits/Electrical_Layout_Plan.pdf',
    mime_type: 'application/pdf',
    size_bytes: 425984,
    category: 'permit',
    tags: ['electrical', 'layout', 'EMA'],
    created_at: '2026-04-12T03:00:00.000Z',
    deleted_at: null,
  },
  {
    id: 'fil-008',
    project_id: 'prj-001',
    uploaded_by: 'usr-002',
    name: 'Defect_MasterBath_Tile_Crack.jpg',
    storage_path: 'projects/prj-001/photos/Defect_MasterBath_Tile_Crack.jpg',
    mime_type: 'image/jpeg',
    size_bytes: 1024000,
    category: 'photo',
    tags: ['defect', 'master-bathroom', 'tile'],
    created_at: '2026-04-18T06:00:00.000Z',
    deleted_at: null,
  },
];

export const mockQuotation: Quotation = {
  id: 'quo-001',
  project_id: 'prj-001',
  version: 1,
  currency: 'SGD',
  total_amount: 48200,
  pdf_file_id: 'fil-001',
  status: 'accepted',
  issued_at: '2026-02-20T04:00:00.000Z',
  accepted_at: '2026-02-22T08:00:00.000Z',
  accepted_by: 'usr-001',
  created_at: '2026-02-20T04:00:00.000Z',
};

export const mockQuotationLines: QuotationLine[] = [
  {
    id: 'qln-001',
    quotation_id: 'quo-001',
    category: 'Hacking',
    description: 'Demolition of existing flooring, kitchen wall tiles, and built-in wardrobes',
    quantity: 1,
    unit: 'lot',
    unit_price: 3800,
    total: 3800,
    sequence: 1,
  },
  {
    id: 'qln-002',
    quotation_id: 'quo-001',
    category: 'Masonry',
    description: 'Brickwork for new kitchen partition wall and waterproofing for 2 bathrooms',
    quantity: 1,
    unit: 'lot',
    unit_price: 4500,
    total: 4500,
    sequence: 2,
  },
  {
    id: 'qln-003',
    quotation_id: 'quo-001',
    category: 'Plumbing',
    description: 'Full piping works for kitchen, 2 bathrooms, and service yard including rain shower mixer set',
    quantity: 1,
    unit: 'lot',
    unit_price: 5200,
    total: 5200,
    sequence: 3,
  },
  {
    id: 'qln-004',
    quotation_id: 'quo-001',
    category: 'Electrical',
    description: 'Full rewiring, new DB box, 42 power points, 18 lighting points, and data points to all rooms',
    quantity: 1,
    unit: 'lot',
    unit_price: 6800,
    total: 6800,
    sequence: 4,
  },
  {
    id: 'qln-005',
    quotation_id: 'quo-001',
    category: 'Carpentry',
    description: 'Kitchen cabinets (upper + lower), 2 built-in wardrobes, shoe cabinet, TV console, and feature wall',
    quantity: 1,
    unit: 'lot',
    unit_price: 18500,
    total: 18500,
    sequence: 5,
  },
  {
    id: 'qln-006',
    quotation_id: 'quo-001',
    category: 'Painting',
    description: 'Full unit plastering, primer, and 2 coats Nippon Odourless All-in-1 paint for all walls and ceilings',
    quantity: 990,
    unit: 'sqft',
    unit_price: 4.5,
    total: 4455,
    sequence: 6,
  },
  {
    id: 'qln-007',
    quotation_id: 'quo-001',
    category: 'Flooring',
    description: 'Supply and install Korean vinyl flooring for living, dining, and 3 bedrooms (approx 650 sqft)',
    quantity: 650,
    unit: 'sqft',
    unit_price: 4.50,
    total: 2925,
    sequence: 7,
  },
  {
    id: 'qln-008',
    quotation_id: 'quo-001',
    category: 'Tiling',
    description: 'Supply and install porcelain floor and wall tiles for kitchen, 2 bathrooms, and service yard',
    quantity: 1,
    unit: 'lot',
    unit_price: 2020,
    total: 2020,
    sequence: 8,
  },
];

export const mockChangeOrders: ChangeOrder[] = [
  {
    id: 'co-001',
    project_id: 'prj-001',
    quotation_id: 'quo-001',
    title: 'Upgrade kitchen cabinet hinges to Blum soft-close',
    description: 'Client requested upgrade from standard hinges to Blum Blumotion soft-close hinges for all kitchen upper and lower cabinets (16 doors total).',
    amount_delta: 480,
    status: 'approved',
    proposed_at: '2026-03-20T04:00:00.000Z',
    proposed_by: 'usr-002',
    decided_at: '2026-03-21T09:00:00.000Z',
    decided_by: 'usr-001',
    created_at: '2026-03-20T04:00:00.000Z',
  },
  {
    id: 'co-002',
    project_id: 'prj-001',
    quotation_id: 'quo-001',
    title: 'Add cove lighting to living room false ceiling',
    description: 'Proposal to add LED cove lighting (warm white 3000K) along the L-shaped false ceiling in the living and dining area. Includes LED strips, driver, and concealment detail.',
    amount_delta: 1200,
    status: 'proposed',
    proposed_at: '2026-04-18T06:00:00.000Z',
    proposed_by: 'usr-002',
    decided_at: null,
    decided_by: null,
    created_at: '2026-04-18T06:00:00.000Z',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-001',
    project_id: 'prj-001',
    invoice_number: 'INV-2026-0041',
    title: 'Deposit (10%)',
    description: 'Initial deposit upon contract signing - 10% of quotation total',
    amount: 4820,
    currency: 'SGD',
    status: 'paid',
    due_date: '2026-03-01',
    issued_at: '2026-02-22T09:00:00.000Z',
    paid_amount: 4820,
    paid_at: '2026-02-28T11:00:00.000Z',
    receipt_file_id: 'fil-006',
    pdf_file_id: null,
    created_by: 'usr-002',
    created_at: '2026-02-22T09:00:00.000Z',
  },
  {
    id: 'inv-002',
    project_id: 'prj-001',
    invoice_number: 'INV-2026-0055',
    title: 'Hacking and masonry milestone',
    description: 'Progress claim upon completion of hacking and masonry works - 25% of quotation total',
    amount: 12050,
    currency: 'SGD',
    status: 'paid',
    due_date: '2026-04-05',
    issued_at: '2026-03-30T04:00:00.000Z',
    paid_amount: 12050,
    paid_at: '2026-04-03T08:30:00.000Z',
    receipt_file_id: null,
    pdf_file_id: null,
    created_by: 'usr-002',
    created_at: '2026-03-30T04:00:00.000Z',
  },
  {
    id: 'inv-003',
    project_id: 'prj-001',
    invoice_number: 'INV-2026-0068',
    title: 'Plumbing and electrical milestone',
    description: 'Progress claim upon completion of plumbing and electrical rough-in - 25% of quotation total',
    amount: 12050,
    currency: 'SGD',
    status: 'overdue',
    due_date: '2026-05-01',
    issued_at: '2026-04-18T04:00:00.000Z',
    paid_amount: 0,
    paid_at: null,
    receipt_file_id: null,
    pdf_file_id: null,
    created_by: 'usr-002',
    created_at: '2026-04-18T04:00:00.000Z',
  },
  {
    id: 'inv-004',
    project_id: 'prj-001',
    invoice_number: 'INV-2026-0089',
    title: 'Carpentry milestone',
    description: 'Progress claim upon completion of carpentry installation - 30% of quotation total',
    amount: 14460,
    currency: 'SGD',
    status: 'draft',
    due_date: '2026-06-01',
    issued_at: null,
    paid_amount: 0,
    paid_at: null,
    receipt_file_id: null,
    pdf_file_id: null,
    created_by: 'usr-002',
    created_at: '2026-04-20T02:00:00.000Z',
  },
];

export const mockChannels: Channel[] = [
  {
    id: 'chn-001',
    project_id: 'prj-001',
    name: 'Main',
    trade: null,
    is_main: true,
    created_at: '2026-02-15T06:00:00.000Z',
  },
  {
    id: 'chn-002',
    project_id: 'prj-001',
    name: 'Carpentry',
    trade: 'carpentry',
    is_main: false,
    created_at: '2026-02-15T06:05:00.000Z',
  },
  {
    id: 'chn-003',
    project_id: 'prj-001',
    name: 'Electrical',
    trade: 'electrical',
    is_main: false,
    created_at: '2026-02-15T06:06:00.000Z',
  },
  {
    id: 'chn-004',
    project_id: 'prj-001',
    name: 'Plumbing',
    trade: 'plumbing',
    is_main: false,
    created_at: '2026-02-15T06:07:00.000Z',
  },
];

export const mockChannelMemberships: ChannelMembership[] = [
  {
    id: 'cmb-001',
    channel_id: 'chn-001',
    user_id: 'usr-001',
    can_post: true,
    joined_at: '2026-02-16T02:15:00.000Z',
  },
  {
    id: 'cmb-002',
    channel_id: 'chn-001',
    user_id: 'usr-002',
    can_post: true,
    joined_at: '2026-02-15T06:00:00.000Z',
  },
  {
    id: 'cmb-003',
    channel_id: 'chn-002',
    user_id: 'usr-002',
    can_post: true,
    joined_at: '2026-02-15T06:05:00.000Z',
  },
  {
    id: 'cmb-004',
    channel_id: 'chn-003',
    user_id: 'usr-002',
    can_post: true,
    joined_at: '2026-02-15T06:06:00.000Z',
  },
  {
    id: 'cmb-005',
    channel_id: 'chn-004',
    user_id: 'usr-002',
    can_post: true,
    joined_at: '2026-02-15T06:07:00.000Z',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    channel_id: 'chn-001',
    user_id: 'usr-002',
    body: 'Hi Sarah, welcome to the project channel! I will be posting updates here as we progress through each phase. Feel free to ask any questions.',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-02-16T03:00:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-002',
    channel_id: 'chn-001',
    user_id: 'usr-001',
    body: 'Thanks Marcus! Excited to get started. Will the hacking really only take 2 weeks?',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-02-16T03:15:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-003',
    channel_id: 'chn-001',
    user_id: 'usr-002',
    body: 'Yes, for a 4-room HDB that is standard. The hacking crew will work Monday to Saturday, 9am to 5pm per HDB regulations. I will send you the HDB renovation permit once it is approved.',
    attachment_file_ids: [],
    reply_to_message_id: 'msg-002',
    created_at: '2026-02-16T03:30:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-004',
    channel_id: 'chn-001',
    user_id: 'usr-002',
    body: 'Hacking completed ahead of schedule! Everything went smoothly. Moving on to masonry next week.',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-03-13T10:00:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-005',
    channel_id: 'chn-002',
    user_id: 'usr-002',
    body: 'Carpentry team: please confirm the laminate samples have been ordered. Client has selected Scandinavian Oak (SO-2208) for the master bedroom wardrobe.',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-04-16T10:00:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-006',
    channel_id: 'chn-002',
    user_id: 'usr-002',
    body: 'Kitchen cabinet carcass material confirmed: 18mm moisture-resistant plywood with HPL laminate faces. Hardware: Blum Blumotion hinges (approved via change order CO-001).',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-04-17T04:00:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-007',
    channel_id: 'chn-003',
    user_id: 'usr-002',
    body: 'Electrical rough-in has started. Wiring for the living room feature wall is pending the client decision on power point layout. Please hold off on concealment until confirmed.',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-04-13T09:00:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-008',
    channel_id: 'chn-003',
    user_id: 'usr-002',
    body: 'DB box upgrade from 8-way to 12-way has been completed. All MCBs labelled.',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-04-18T07:00:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-009',
    channel_id: 'chn-004',
    user_id: 'usr-002',
    body: 'Plumbing rough-in complete. Water pressure test passed for both bathrooms and kitchen. No leaks detected.',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-04-10T10:00:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
  {
    id: 'msg-010',
    channel_id: 'chn-004',
    user_id: 'usr-002',
    body: 'Rain shower mixer set for master bathroom has been installed. Franke sink rough-in done for kitchen. Awaiting final fixture installation after tiling.',
    attachment_file_ids: [],
    reply_to_message_id: null,
    created_at: '2026-04-10T11:30:00.000Z',
    edited_at: null,
    deleted_at: null,
  },
];

export const mockDefects: Defect[] = [
  {
    id: 'def-001',
    project_id: 'prj-001',
    reported_by: 'usr-001',
    title: 'Hairline crack on master bathroom wall tile',
    description: 'Noticed a hairline crack running diagonally across one of the wall tiles behind the vanity mirror in the master bathroom. Tile is about 1.5m from the floor on the left wall.',
    location_text: 'Master bathroom, left wall behind vanity mirror',
    floor_plan_pin: null,
    photo_file_ids: ['fil-008'],
    assigned_trade: 'tiling',
    assigned_to: null,
    status: 'open',
    scheduled_for: null,
    resolved_at: null,
    signed_off_at: null,
    signed_off_by: null,
    created_at: '2026-04-18T06:00:00.000Z',
  },
  {
    id: 'def-002',
    project_id: 'prj-001',
    reported_by: 'usr-002',
    title: 'Common bathroom floor trap not aligned with tile slope',
    description: 'Floor trap in the common bathroom is slightly raised relative to the surrounding tiles, causing water to pool near the door instead of draining properly.',
    location_text: 'Common bathroom, floor trap area near entrance',
    floor_plan_pin: null,
    photo_file_ids: [],
    assigned_trade: 'plumbing',
    assigned_to: null,
    status: 'fixed',
    scheduled_for: '2026-04-12',
    resolved_at: '2026-04-14T08:00:00.000Z',
    signed_off_at: null,
    signed_off_by: null,
    created_at: '2026-04-08T05:00:00.000Z',
  },
  {
    id: 'def-003',
    project_id: 'prj-001',
    reported_by: 'usr-001',
    title: 'Uneven cement screed patch in kitchen',
    description: 'Small area (approx 30cm x 30cm) near the kitchen entrance has uneven cement screed. Noticed a bump when walking over it.',
    location_text: 'Kitchen entrance, right side when entering from dining area',
    floor_plan_pin: null,
    photo_file_ids: [],
    assigned_trade: 'masonry',
    assigned_to: null,
    status: 'signed_off',
    scheduled_for: '2026-03-30',
    resolved_at: '2026-03-31T07:00:00.000Z',
    signed_off_at: '2026-04-01T09:00:00.000Z',
    signed_off_by: 'usr-001',
    created_at: '2026-03-28T06:00:00.000Z',
  },
];

export function getMockProject(): Project {
  return mockProject;
}

export function getMockPhases(): Phase[] {
  return [...mockPhases].sort((a, b) => a.sequence - b.sequence);
}

export function getMockDecisions(): Decision[] {
  return mockDecisions;
}

export function getMockQuotation(): Quotation & { lines: QuotationLine[] } {
  return { ...mockQuotation, lines: mockQuotationLines };
}

export function getMockInvoices(): Invoice[] {
  return mockInvoices;
}

export function getMockDefects(): Defect[] {
  return mockDefects;
}

export function getMockChannels(): Channel[] {
  return mockChannels;
}

export function getMockFiles(): ProjectFile[] {
  return mockFiles;
}

export function getCurrentPhase(): Phase | undefined {
  return mockPhases.find((p) => p.status === 'in_progress');
}

export function getPendingDecisions(): Decision[] {
  return mockDecisions.filter(
    (d) => d.status === 'pending' || d.status === 'overdue',
  );
}

export function getOverdueInvoices(): Invoice[] {
  return mockInvoices.filter((i) => i.status === 'overdue');
}

export const mockAuditLog: AuditLog[] = [
  {
    id: 'aud-001',
    project_id: 'prj-001',
    actor_user_id: 'usr-002',
    action: 'project_created',
    entity_type: 'project',
    entity_id: 'prj-001',
    before: null,
    after: null,
    metadata: null,
    occurred_at: '2026-02-15T06:00:00.000Z',
  },
  {
    id: 'aud-002',
    project_id: 'prj-001',
    actor_user_id: 'usr-002',
    action: 'phase_started',
    entity_type: 'phase',
    entity_id: 'phs-001',
    before: null,
    after: { status: 'in_progress' },
    metadata: null,
    occurred_at: '2026-03-03T08:00:00.000Z',
  },
  {
    id: 'aud-003',
    project_id: 'prj-001',
    actor_user_id: 'usr-002',
    action: 'phase_completed',
    entity_type: 'phase',
    entity_id: 'phs-001',
    before: { status: 'in_progress' },
    after: { status: 'complete' },
    metadata: null,
    occurred_at: '2026-03-13T10:00:00.000Z',
  },
  {
    id: 'aud-004',
    project_id: 'prj-001',
    actor_user_id: 'usr-002',
    action: 'decision_created',
    entity_type: 'decision',
    entity_id: 'dec-002',
    before: null,
    after: null,
    metadata: null,
    occurred_at: '2026-03-18T04:00:00.000Z',
  },
  {
    id: 'aud-005',
    project_id: 'prj-001',
    actor_user_id: 'usr-001',
    action: 'decision_decided',
    entity_type: 'decision',
    entity_id: 'dec-002',
    before: { status: 'pending' },
    after: { status: 'decided' },
    metadata: null,
    occurred_at: '2026-03-22T14:00:00.000Z',
  },
  {
    id: 'aud-006',
    project_id: 'prj-001',
    actor_user_id: 'usr-002',
    action: 'invoice_issued',
    entity_type: 'invoice',
    entity_id: 'inv-002',
    before: null,
    after: { status: 'issued', amount: 12050 },
    metadata: null,
    occurred_at: '2026-03-30T04:00:00.000Z',
  },
  {
    id: 'aud-007',
    project_id: 'prj-001',
    actor_user_id: 'usr-001',
    action: 'invoice_paid',
    entity_type: 'invoice',
    entity_id: 'inv-002',
    before: { status: 'issued' },
    after: { status: 'paid', paid_amount: 12050 },
    metadata: null,
    occurred_at: '2026-04-03T08:30:00.000Z',
  },
  {
    id: 'aud-008',
    project_id: 'prj-001',
    actor_user_id: 'usr-001',
    action: 'defect_opened',
    entity_type: 'defect',
    entity_id: 'def-002',
    before: null,
    after: { status: 'open' },
    metadata: null,
    occurred_at: '2026-04-08T05:00:00.000Z',
  },
  {
    id: 'aud-009',
    project_id: 'prj-001',
    actor_user_id: 'usr-002',
    action: 'defect_resolved',
    entity_type: 'defect',
    entity_id: 'def-002',
    before: { status: 'open' },
    after: { status: 'fixed' },
    metadata: null,
    occurred_at: '2026-04-14T08:00:00.000Z',
  },
  {
    id: 'aud-010',
    project_id: 'prj-001',
    actor_user_id: 'usr-001',
    action: 'defect_opened',
    entity_type: 'defect',
    entity_id: 'def-001',
    before: null,
    after: { status: 'open' },
    metadata: null,
    occurred_at: '2026-04-18T06:00:00.000Z',
  },
];

export function getMockAuditLog(): AuditLog[] {
  return [...mockAuditLog].sort(
    (a, b) => new Date(b.occurred_at).getTime() - new Date(a.occurred_at).getTime(),
  );
}
